place_timer: 120

##How high and low the canvas zone should go. Recommended: 10-50
canvas_zone_limits: 10

##Whitelisted blocks
canvas_blocks:
  - CYAN_WOOL
  - PURPLE_WOOL
  - BLUE_WOOL
  - BROWN_WOOL
  - GREEN_WOOL
  - RED_WOOL
  - BLACK_WOOL
  - GRAY_WOOL
  - LIGHT_GRAY_WOOL
  - WHITE_WOOL
  - ORANGE_WOOL
  - PINK_WOOL
  - LIGHT_BLUE_WOOL
  - YELLOW_WOOL
  - LIME_WOOL
  - MAGENTA_WOOL

invis_player: true



##Messages
msg_timernotfinished: "&cYou can only place blocks every {seconds} seconds!"
msg_outsideofcanvas: "&cYou cannot place blocks outside the canvas!"
msg_insidefromoutsideofcanvas: "&cYou cannot place blocks inside the canvas from outside the canvas!"
msg_canvasenter: "&aYou entered the canvas!"
msg_canvasleave: "&cYou left the canvas!"
msg_noteleport: "&cPlease leave the canvas before teleporting out."

##Do not touch this unless you know what you are doing!
canvas: "null"