name: RPlace
version: '${project.version}'
main: me.evilterabite.rplace.RPlace
api-version: 1.19
authors: [ evilterabite ]
description: Reddit's R/Place subreddit from 2017 and 2022 in Minecraft

commands:
  canvas:
    description: Opens the canvas creation GUI
  palette:
    description: Opens the block palette GUI
